/**
 * generated by Xtext 2.9.2
 */
package org.eclipse.docker.language.container;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Container Defination</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.docker.language.container.RunContainerDefination#getSequence <em>Sequence</em>}</li>
 * </ul>
 *
 * @see org.eclipse.docker.language.container.ContainerPackage#getRunContainerDefination()
 * @model
 * @generated
 */
public interface RunContainerDefination extends EObject
{
  /**
   * Returns the value of the '<em><b>Sequence</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.docker.language.container.Container}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sequence</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence</em>' reference list.
   * @see org.eclipse.docker.language.container.ContainerPackage#getRunContainerDefination_Sequence()
   * @model
   * @generated
   */
  EList<Container> getSequence();

} // RunContainerDefination
