/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.container.impl;

import java.util.Collection;

import org.eclipse.docker.language.container.BuildImagesExecution;
import org.eclipse.docker.language.container.ContainerPackage;
import org.eclipse.docker.language.container.Image;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Build Images Execution</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.docker.language.container.impl.BuildImagesExecutionImpl#getSequence <em>Sequence</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BuildImagesExecutionImpl extends MinimalEObjectImpl.Container implements BuildImagesExecution
{
  /**
   * The cached value of the '{@link #getSequence() <em>Sequence</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSequence()
   * @generated
   * @ordered
   */
  protected EList<Image> sequence;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BuildImagesExecutionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ContainerPackage.Literals.BUILD_IMAGES_EXECUTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Image> getSequence()
  {
    if (sequence == null)
    {
      sequence = new EObjectResolvingEList<Image>(Image.class, this, ContainerPackage.BUILD_IMAGES_EXECUTION__SEQUENCE);
    }
    return sequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ContainerPackage.BUILD_IMAGES_EXECUTION__SEQUENCE:
        return getSequence();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ContainerPackage.BUILD_IMAGES_EXECUTION__SEQUENCE:
        getSequence().clear();
        getSequence().addAll((Collection<? extends Image>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ContainerPackage.BUILD_IMAGES_EXECUTION__SEQUENCE:
        getSequence().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ContainerPackage.BUILD_IMAGES_EXECUTION__SEQUENCE:
        return sequence != null && !sequence.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BuildImagesExecutionImpl
