/*
 * generated by Xtext 2.9.2
 */
package org.eclipse.docker.language.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.docker.language.parser.antlr.internal.InternalContainerParser;
import org.eclipse.docker.language.services.ContainerGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ContainerParser extends AbstractAntlrParser {

	@Inject
	private ContainerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalContainerParser createParser(XtextTokenStream stream) {
		return new InternalContainerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Docker";
	}

	public ContainerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ContainerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
