/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.ui;

import com.google.inject.Binder;
import com.google.inject.Scopes;
import com.google.inject.binder.AnnotatedBindingBuilder;
import org.eclipse.docker.language.ui.AbstractContainerUiModule;
import org.eclipse.docker.language.ui.launch.DockerConsole;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ContainerUiModule extends AbstractContainerUiModule {
  @Override
  public void configure(final Binder binder) {
    AnnotatedBindingBuilder<DockerConsole> _bind = binder.<DockerConsole>bind(DockerConsole.class);
    _bind.in(Scopes.SINGLETON);
    super.configure(binder);
  }
  
  public ContainerUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
