/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.tests;

import com.google.inject.Inject;
import org.eclipse.docker.language.container.Docker;
import org.eclipse.docker.language.tests.ContainerInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ContainerInjectorProvider.class)
@SuppressWarnings("all")
public class ContainerParsingTest {
  @Inject
  private ParseHelper<Docker> parseHelper;
  
  @Test
  public void loadModel() {
  }
}
