/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractContainerScopeProvider extends DelegatingScopeProvider {
}
