/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.tests

import com.google.inject.Inject
import org.eclipse.docker.language.container.Docker
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ContainerInjectorProvider)
class ContainerParsingTest{

	@Inject
	ParseHelper<Docker> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
