/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.validation;

import org.eclipse.docker.language.validation.AbstractContainerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ContainerValidator extends AbstractContainerValidator {
}
