/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language.tests;

import com.google.inject.Inject;
import org.eclipse.docker.language.tests.ContainerInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ContainerInjectorProvider.class)
@SuppressWarnings("all")
public class ContainerParsingTest {
  @Inject
  private /* ParseHelper<Docker> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field ContainerParsingTest.parseHelper refers to the missing type Docker");
  }
}
