/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.docker.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ContainerStandaloneSetup extends ContainerStandaloneSetupGenerated {

	def static void doSetup() {
		new ContainerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
